steps:
  # 1) Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/book-lering",
        "--build-arg",
        "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL",
        "--build-arg",
        "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY",
        ".",
      ]

  # 2) Push image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/book-lering"]

  # 3) Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloudsdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "book-lering",
        "--image",
        "gcr.io/$PROJECT_ID/book-lering",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - gcr.io/$PROJECT_ID/book-lering
